language: php

matrix:
  include:
    - php: 7.3
      env: COMPOSER_FLAGS=--prefer-lowest
    - php: 7.4
    - php: 8.0
    - php: 8.1
      env: STATIC_ANALYSIS=true
    - php: 8.1
      env: PHPUNIT_FLAGS="--coverage-clover coverage.xml"

install:
  - composer update $COMPOSER_FLAGS

before_script:
  - git --version

script:
  - if [[ $PHPUNIT_FLAGS != "" ]]; then phpenv config-rm xdebug.ini; fi
  - vendor/bin/phpunit $PHPUNIT_FLAGS
  # disable xdebug if not needed
  - if [[ $STATIC_ANALYSIS == true ]]; then vendor/bin/phpstan; fi

after_script:
  # upload coverage.xml to Coveralls
  - |
    if [[ $PHPUNIT_FLAGS != "" ]]; then
        wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar;
        php coveralls.phar --verbose;
    fi

notifications:
  email: false
