name: CI

on:
  push:
    branches: [ 4.x ]
  pull_request:
    branches: [ 4.x ]

jobs:
  main:
    runs-on: ubuntu-latest
    name: All tools
    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: composer update -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Run PHPStan
      run: vendor/bin/phpstan
    - name: Run phpcs
      run: vendor/bin/phpcs

  other:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ '7.4', '8.0', '8.1', '8.2', '8.3', '8.4', '8.5' ]
    name: PHP ${{ matrix.php-versions }}
    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: none

    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: composer update -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: PHPUnit
      run: vendor/bin/phpunit

